/* By Pascal Tene
 * File Integrity Checker using SHA-256 Hashing 
 * * We must ansure that the following five key properties are met:
 * 1. One-Way (Pre-image Resistance)
 * 2. Deterministic
 * 3. Fast (Computational Efficiency)
 * 4. Avalanche Effect
 * 5. Collision Resistance
 *
 * The hash generated by this program will be used to help guarantee the integrity
 * of files on the system it is run on. By comparing the current hash of a file
 * with a known good hash, any unauthorized modifications can be detected.
 */
#include <iostream>
#include <fstream>
#include <vector>
#include <chrono> // For timing the process
#include <iomanip> // For printing floating-point numbers
#include "picosha2.h" // a SHA256 hash generator for C++ with no external dependencies 

int main() {
    // Define the file you want to hash
    std::string filePath = "/Users/p.tene/Downloads/Postgres-2.8.5-17.dmg"; 
    
    std::ifstream f(filePath, std::ios::binary | std::ios::ate); // Added | std::ios::ate for easy size check
    
    // Check if file exists
    if (!f.is_open()) {
        std::cerr << "Error: Could not find file " << filePath << std::endl;
        return 1;
    }

    // Get File Size (using position from std::ios::ate)
    std::streampos fileSize = f.tellg();
    f.seekg(0, std::ios::beg); // Reset file pointer to the beginning for reading
    
    // Prepare a vector to hold the hash result (32 bytes for SHA-256)
    std::vector<unsigned char> hash(picosha2::k_digest_size);
    
    // Start Timing
    auto start_time = std::chrono::high_resolution_clock::now();

    // Calculate hash directly from the file stream
    picosha2::hash256(f, hash.begin(), hash.end());
    
    // Stop Timing
    auto end_time = std::chrono::high_resolution_clock::now();
    
    // Calculate Duration
    auto duration = std::chrono::duration_cast<std::chrono::microseconds>(end_time - start_time).count();
    double duration_ms = static_cast<double>(duration) / 1000.0;


    // Convert to hex string and print
    std::string hex_str = picosha2::bytes_to_hex_string(hash.begin(), hash.end());
    
    // Output Results
    std::cout << "--- File Integrity Check Results ---" << std::endl;
    std::cout << "File:    " << filePath << "\n";
    std::cout << "Size:    " << fileSize << " bytes\n";
    std::cout << "SHA-256: " << hex_str << std::endl;
    std::cout << "Time:    " << std::fixed << std::setprecision(3) << duration_ms << " ms" << std::endl;
    std::cout << "------------------------------------" << std::endl;
    
    return 0;
}